public enum EntityType {
    Aircraft,
    AircraftFighter,
    AircraftMulti,
    AircraftAttack,
    AircraftStrato,
    AircraftSpace,
    Ground,
    GroundBase,
    GroundRadar,
    GroundSite,
    GroundBuilding,
    Hydrofoil,
    Carrier,
    Satellite,
}
